### ISSUE TITLE
[1.20.1] World fails to load with "Invalid resource path" Needs GDLauncher Relative Path Fix Applied to 1.20.1

### ISSUE THREAD

**Issue by JoelZBub** [Lythom/capsule#104]
MC Version: 1.20.1 (Possibly others? Haven't tested)
Forge Version : 47.2.4 - 42.7.8 (versions tested)
Capsule version:  1.20.1-7.0.101

When creating a new world, the game closes on world load with "Connection Lost Invalid Player Data" screen.

<details>
  <summary>Relevant Log Info Here</summary>
  
  Here are the latest.log outputs upon world join:
  
  ```java
  [09:11:12] [Server thread/ERROR]: Couldn't resolve proper location: c-joelzbub-config_capsule_starters__stater_oak_hut-1
net.minecraft.ResourceLocationException: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.schematic
	at capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:173) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.loadTemplateFile(CapsuleTemplateManager.java:95) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.lambda$getTemplate$0(CapsuleTemplateManager.java:57) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at capsule.structure.CapsuleTemplateManager.getTemplate(CapsuleTemplateManager.java:56) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.getUniqueName(StructureSaver.java:564) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:442) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.__StarterLoot_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.6-universal.jar%23163!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:11:12] [Server thread/ERROR]: Couldn't resolve proper location: c-joelzbub-config_capsule_starters__stater_oak_hut-1
net.minecraft.ResourceLocationException: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.nbt
	at capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:173) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.loadTemplateFile(CapsuleTemplateManager.java:95) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.lambda$getTemplate$0(CapsuleTemplateManager.java:58) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at capsule.structure.CapsuleTemplateManager.getTemplate(CapsuleTemplateManager.java:56) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.getUniqueName(StructureSaver.java:564) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:442) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.__StarterLoot_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.6-universal.jar%23163!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:11:12] [Server thread/ERROR]: Couldn't resolve proper location: c-joelzbub-config_capsule_starters__stater_oak_hut-1
net.minecraft.ResourceLocationException: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.schematic
	at capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:173) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.loadTemplateFile(CapsuleTemplateManager.java:95) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.lambda$getTemplate$0(CapsuleTemplateManager.java:57) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at capsule.structure.CapsuleTemplateManager.getTemplate(CapsuleTemplateManager.java:56) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.getOrCreateTemplate(CapsuleTemplateManager.java:44) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:605) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:598) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:455) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.__StarterLoot_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.6-universal.jar%23163!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:11:12] [Server thread/ERROR]: Couldn't resolve proper location: c-joelzbub-config_capsule_starters__stater_oak_hut-1
net.minecraft.ResourceLocationException: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.nbt
	at capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:173) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.loadTemplateFile(CapsuleTemplateManager.java:95) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.lambda$getTemplate$0(CapsuleTemplateManager.java:58) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at capsule.structure.CapsuleTemplateManager.getTemplate(CapsuleTemplateManager.java:56) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.structure.CapsuleTemplateManager.getOrCreateTemplate(CapsuleTemplateManager.java:44) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:605) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:598) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:455) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at capsule.loot.__StarterLoot_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[Capsule-1.20.1-7.0.101.jar%23157!/:1.20.1-7.0.101]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.6-universal.jar%23163!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:11:12] [Server thread/ERROR]: Exception caught during firing event: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.nbt
	Index: 4
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4677/0x000000080178e000@76f3e935
		2: ASM: net.minecraftforge.common.ForgeInternalHandler@3a140549 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: LOWEST
		4: ASM: class capsule.loot.StarterLoot playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
net.minecraft.ResourceLocationException: Invalid resource path: ..\\..\\instances\\Capsule Test\\saves\\New World\\capsules\\c-joelzbub-config_capsule_starters__stater_oak_hut-1.nbt
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:173)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.structure.CapsuleTemplateManager.writeToFile(CapsuleTemplateManager.java:140)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.StructureSaver.duplicateTemplate(StructureSaver.java:615)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.StructureSaver.duplicateTemplate(StructureSaver.java:598)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:455)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49)
	at TRANSFORMER/capsule@1.20.1-7.0.101/capsule.loot.__StarterLoot_playerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.6/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
  ```
  
</details>

This issue is present using GDLauncher, but not ATLauncher.

This is a likely duplicate of an issue present in earlier versions of Capsule:
#71
#77

**Comment by JoelZBub** [comment]
#107

**Comment by JoelZBub** [comment]
Fixed in https://github.com/Lythom/capsule/commit/2f21429b58e0012a330bcc86bffb3264a9451773
