### ISSUE TITLE
Incompatible w/ McMultipart

### ISSUE THREAD

**Issue by WenXin20** [Lythom/capsule#15]
Minecraft v1.12.2
Forge v14.23.5.2838
[EDX Multipart](https://www.curseforge.com/minecraft/mc-mods/edx-multipart) v1.1.1
[McMultipart ](https://www.curseforge.com/minecraft/mc-mods/mcmultipart)v2.5.3
Capsule v3.2.103

After adding a double slab smooth stone to the capsule, it failed to place the capsule contents. This is because EDX Multipart converts double slabs to McMultipart blocks to be able to combine different slabs into one block. Is McMultipart compatibility possible?
```
[20:13:05] [Server thread/ERROR]: Couldn't deploy the capsule
java.lang.NullPointerException: null
	at mcmultipart.util.MCMPWorldWrapper.<init>(MCMPWorldWrapper.java:59) ~[MCMPWorldWrapper.class:?]
	at mcmultipart.multipart.PartInfo.refreshWorld(PartInfo.java:145) ~[PartInfo.class:?]
	at mcmultipart.multipart.PartInfo.setState(PartInfo.java:118) ~[PartInfo.class:?]
	at mcmultipart.multipart.PartInfo.<init>(PartInfo.java:64) ~[PartInfo.class:?]
	at mcmultipart.block.TileMultipartContainer.readParts(TileMultipartContainer.java:387) ~[TileMultipartContainer.class:?]
	at mcmultipart.block.TileMultipartContainer.readFromNBT(TileMultipartContainer.java:295) ~[TileMultipartContainer.class:?]
	at capsule.structure.CapsuleTemplate.spawnBlocksAndEntities(CapsuleTemplate.java:475) ~[CapsuleTemplate.class:?]
	at capsule.StructureSaver.deploy(StructureSaver.java:267) [StructureSaver.class:?]
	at capsule.helpers.Capsule.deployCapsule(Capsule.java:144) [Capsule.class:?]
	at capsule.helpers.Capsule.handleEntityItemOnGround(Capsule.java:401) [Capsule.class:?]
	at capsule.items.CapsuleItem.onEntityItemUpdate(CapsuleItem.java:672) [CapsuleItem.class:?]
	at net.minecraft.entity.item.EntityItem.onUpdate(EntityItem.java:87) [acl.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1955) [amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zbo000(World.java:4118) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1759) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20:13:06] [Client thread/INFO]: [CHAT] A technical error occured while using the Capsule Mod. Please check the server logs.
```

**Comment by Lythom** [comment]
Hello !
I don't think I tested capsule with McMultipart so it can be.
Does McMultipart works with vanilla structure block (ie. saving an area containing so McMultipart slabs and loading it elsewhere) ?
Capsule relies on the same mechanics as structure block so if McMultipart works with structure blocks I'll fix capsule, if it doesn't then we'd better open a ticket on McMultipart project to add structure blocks compatibility.

**Comment by WenXin20** [comment]
I'm not sure, I've never used the structure blocks before. I might be able to try it out tonight or tomorrow.

**Comment by WenXin20** [comment]
Just tried it out and McMultipart crashes with structure blocks.
I'll report it to them.

**Comment by Lythom** [comment]
Closing due to inactivity
