### ISSUE TITLE
1.18.2 Invalid resource path on GDLauncher

### ISSUE THREAD

**Issue by Raidobw2** [Lythom/capsule#71]
It appears GDLauncher is using relative paths which seems to be causing an error within the Capsule mod.

Versions:
Minecraft `1.18.2`
Forge `40.1.52`
Capsule `Capsule-1.18.2-6.0.84.jar`
Modpack `FTB Plexiglass Mountain 1.1.1`

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1039

-----------------

Truncated log which should hold the information you need:
https://paste.feed-the-beast.com/view/e17b245a
If you need more information, it is held in the linked issue above, there are 2 full log files, or ask me

```
[00:51:37] [Server thread/ERROR]: Couldn't place player in world
net.minecraft.ResourceLocationException: Invalid resource path: ..\..\instances\FTB Plexiglass Mountain\saves\Plexi\capsules\c-exodiajedi-config_capsule_starters__stater_acacia_hut-0.nbt
        at capsule.structure.CapsuleTemplateManager.resolvePath(CapsuleTemplateManager.java:164) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.structure.CapsuleTemplateManager.writeToFile(CapsuleTemplateManager.java:131) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:616) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.StructureSaver.duplicateTemplate(StructureSaver.java:599) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.helpers.Capsule.createLinkedCapsuleFromReward(Capsule.java:461) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.loot.StarterLoot.giveAllStarters(StarterLoot.java:64) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
        at capsule.loot.StarterLoot.playerLogin(StarterLoot.java:49) ~[Capsule-1.18.2-6.0.84.jar%2383!/:1.18.2-6.0.84]
```

P.S.: To my knowledge we do not use custom starter huts, these should be the default ones shipped within the mod

I think there's a small typo maybe in the nbt files too, "stater" hut should be "starter" hut

Thank you in advance for investigating it!

**Comment by Lythom** [comment]
Thanks for reporting, I'll have a look (can't tell when though).

**Comment by ExodiaJedi** [comment]
The error happens when trying to create a new world and place a "starter house" into the player inventory.
Checked in the save location for that instance.
`..\..\instances\<Instance Name>\saves\<Save Name>\`
It seems that the directory is created, but the file can't be copied for some reason (could be the typo documented above).
`..\..\instances\<Instance Name>\saves\<Save Name>\capsules\`

I have tried multiple instances, and each time it will reference a different starter house from the available ones contained in the directory below:
`..\..\instances\<Instance Name>\config\capsule\starters`

**Comment by Molier** [comment]
just bumping to check if any logs or something are needed? having same problem and could provide some bugfixing assistance, as for now i just removed it from modlist
